### ISSUE TITLE
Question: Generating directories

### ISSUE THREAD

**Issue by ArthurMoore85** [ffaraone/vscode-pyfilesgen#1]
Love the extension, and use it a lot.
I wondered if it was possible to generate directories too?

Almost all my work involves Django, but I tend to slightly tweak my module setup.
Instead of a views.py and models.py, I tend to create models and views as modules, each containing separate models/views python files.
Is it possible to have it generate it that way? For instance instead of it generating views.py, that it would generate a subdir named views, and a __init__.py file inside it?

**Comment by ffaraone** [comment]
The extension already do that. Right click on the directory in which you want to create your python module, choose "Py Files Generator" then "Python modules" and then type the name of the module you want to create. It should generate the module with the __init__.py inside of it.
See the "Usage" section of the readme. If you like my extension, please write a review [here](https://marketplace.visualstudio.com/items?itemName=ffaraone.pyfilesgen).
